version: "3"
services:
  database:
    env_file: .env
    image: postgres:latest
    container_name: database_agro
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
    networks:
      - agro-net
    restart: on-failure
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_agro
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    command: sh -c "
      python manage.py migrate
      && python manage.py loaddata adminuser.json state.json
      && python manage.py collectstatic --noinput
      && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload"
    expose:
      - 8000
    depends_on:
      - database
    networks:
      - agro-net
    volumes:
      - .:/backend
      - ./logs:/api/logs
      - staticfiles:/api/staticfiles
      - media:/api/media
    restart: on-failure
    stdin_open: true
    tty: true

  proxy:
    image: nginx:latest
    restart: always
    networks:
      - agro-net
    ports:
      - 80:80
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/api/staticfiles
      - media:/api/media
      - ./logs/proxy_error.log:/var/log/nginx/error.log
      - ./logs/access.log:/var/log/nginx/access.log
    depends_on:
      - backend

networks:
  agro-net:
    driver: bridge

volumes:
  staticfiles:
  media:
  postgres-data: