# Generated by Django 4.2.10 on 2024-03-01 03:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "personal_document",
                    models.CharField(help_text="Documento pessoal da usuario, podendo ser CPF ou CNPJ", max_length=25),
                ),
                ("name", models.CharField(help_text="Nome do produtor", max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Customter",
                "verbose_name_plural": "Customers",
                "db_table": "customer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmProperty",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Nome da fazenda ou propriedade", max_length=256)),
                ("city", models.CharField(help_text="Nome da cidade", max_length=128)),
                (
                    "area",
                    models.DecimalField(decimal_places=2, help_text="Área total em hectares da fazenda", max_digits=5),
                ),
                (
                    "farming_area",
                    models.DecimalField(decimal_places=2, help_text="Área agricultável em hectares", max_digits=5),
                ),
                (
                    "plant_area",
                    models.DecimalField(decimal_places=2, help_text="Área de vegetação em hectares", max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Campo relacional do cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_farms",
                        to="agrobusiness.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Property",
                "verbose_name_plural": "Farm Properties",
                "db_table": "farm_property",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("acronym", models.CharField(help_text="Sigla do estado", max_length=2)),
                ("name", models.CharField(help_text="Nome do estado", max_length=64)),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "state",
                "ordering": ["acronym"],
            },
        ),
        migrations.CreateModel(
            name="PlantingType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("plant_name", models.CharField(help_text="Tipo de cultivo", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        help_text="Campo relacional de cultivo da fazenda",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultivated_fields",
                        to="agrobusiness.farmproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planting Type",
                "verbose_name_plural": "Planting Types",
                "db_table": "planting_type",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="farmproperty",
            name="state",
            field=models.ForeignKey(
                help_text="Campo relacional do estado da fazenda",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="state_farms",
                to="agrobusiness.state",
            ),
        ),
    ]
